# Generated by Django 4.0.1 on 2022-01-18 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('author_id', models.UUIDField(verbose_name="Author's Tenure UUID")),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ARRIVED', 'Arrived'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In Progress'), ('ONLEAVE', 'Onleave'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], max_length=16, verbose_name='Status')),
                ('type', models.CharField(choices=[('AMB', 'Ambulatory'), ('EMER', 'Emergency'), ('FLD', 'Field'), ('HH', 'Home Health'), ('IMP', 'Inpatient Encounter'), ('ACUTE', 'Inpatient Acute'), ('NONAC', 'Inpatient Non-Acute'), ('OBSENC', 'Observation Encounter'), ('PRENC', 'Pre-Admission'), ('SS', 'Short Stay'), ('VR', 'Virtual')], max_length=8, verbose_name='Type')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Visit Start')),
                ('end', models.DateTimeField(null=True, verbose_name='Visit End')),
                ('clinical_notes', models.TextField(verbose_name='Clinical Notes')),
                ('attachment', models.FileField(upload_to='attachments/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Diagnosis Code')),
                ('description', models.TextField(verbose_name='Diagnosis Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='ICD10 Category')),
                ('title', models.TextField(verbose_name='Category Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LOINC',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='LOINC Code')),
                ('component', models.CharField(max_length=256, verbose_name='Component')),
                ('attribute', models.CharField(max_length=32, verbose_name='Attribute/Property')),
                ('timing', models.CharField(max_length=32, verbose_name='Timing')),
                ('system', models.CharField(max_length=256, verbose_name='System')),
                ('scale', models.CharField(max_length=8, verbose_name='Scale')),
                ('method', models.CharField(max_length=256, verbose_name='Method')),
                ('long_common_name', models.TextField(verbose_name='Long Common Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('DISCOURAGED', 'Discouraged'), ('TRIAL', 'Trial')], max_length=16, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RxTerm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='RXCUI')),
                ('name', models.TextField(verbose_name='Display Name')),
                ('route', models.CharField(max_length=64, verbose_name='Route')),
                ('strength', models.CharField(max_length=256, verbose_name='Strength')),
                ('form', models.CharField(max_length=64, verbose_name='Form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('patient_id', models.UUIDField(verbose_name='Patient UUID')),
                ('facility_id', models.UUIDField(verbose_name='Health Facility UUID')),
                ('type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('DENTAL', 'Dental'), ('OPTICAL', 'Optical')], max_length=16, verbose_name='Visit Type')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Visit Start')),
                ('end', models.DateTimeField(null=True, verbose_name='Visit End')),
                ('invoice_number', models.CharField(max_length=32, verbose_name='Invoice Number')),
                ('invoice_attachment', models.FileField(upload_to='attachments/')),
                ('synced', models.BooleanField(default=False, verbose_name='Synced with record registry?')),
                ('primary_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.icd10')),
                ('secondary_diagnoses', models.ManyToManyField(related_name='secondary_diagnoses', to='facility.ICD10')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid?')),
                ('description', models.TextField(verbose_name='Description')),
                ('frequency', models.IntegerField(verbose_name='Frequency')),
                ('duration', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=8, verbose_name='Duration')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.rxterm')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='facility.encounter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('result', models.CharField(max_length=256, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='observations', to='facility.encounter')),
                ('loinc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.loinc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='icd10',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.icd10category'),
        ),
        migrations.CreateModel(
            name='HCPCS',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('code', models.CharField(max_length=16, verbose_name='HCPCS Code')),
                ('seq_num', models.CharField(default='0010', max_length=8, verbose_name='Sequence Number')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'unique_together': {('code', 'seq_num')},
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encounters', to='facility.visit'),
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid?')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='charge_items', to='facility.encounter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.hcpcs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
