# Generated by Django 4.0.1 on 2022-01-23 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ARRIVED', 'Arrived'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In Progress'), ('ONLEAVE', 'Onleave'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('type', models.CharField(choices=[('AMB', 'Ambulatory'), ('EMER', 'Emergency'), ('FLD', 'Field'), ('HH', 'Home Health'), ('IMP', 'Inpatient Encounter'), ('ACUTE', 'Inpatient Acute'), ('NONAC', 'Inpatient Non-Acute'), ('OBSENC', 'Observation Encounter'), ('PRENC', 'Pre-Admission'), ('SS', 'Short Stay'), ('VR', 'Virtual')], max_length=8)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('clinical_notes', models.TextField()),
                ('attachment', models.FileField(upload_to='attachments/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('title', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LOINC',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('component', models.CharField(max_length=256)),
                ('attribute', models.CharField(max_length=32)),
                ('timing', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=256)),
                ('scale', models.CharField(max_length=8)),
                ('method', models.CharField(max_length=256)),
                ('long_common_name', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('DISCOURAGED', 'Discouraged'), ('TRIAL', 'Trial')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RxTerm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.TextField()),
                ('route', models.CharField(max_length=64)),
                ('strength', models.CharField(max_length=256)),
                ('form', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_id', models.UUIDField()),
                ('facility_id', models.UUIDField()),
                ('type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('DENTAL', 'Dental'), ('OPTICAL', 'Optical')], max_length=16)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('invoice_number', models.CharField(max_length=32)),
                ('invoice_attachment', models.FileField(upload_to='attachments/')),
                ('is_synced', models.BooleanField(default=False)),
                ('primary_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.icd10')),
                ('secondary_diagnoses', models.ManyToManyField(related_name='secondary_diagnoses', to='facility.ICD10')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('frequency', models.IntegerField()),
                ('duration', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=8)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.rxterm')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='facility.encounter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('result', models.CharField(max_length=256, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='observations', to='facility.encounter')),
                ('loinc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.loinc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='icd10',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.icd10category'),
        ),
        migrations.CreateModel(
            name='HCPCS',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=16)),
                ('seq_num', models.CharField(default='0010', max_length=8)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('code', 'seq_num')},
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='encounters', to='facility.visit'),
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='charge_items', to='facility.encounter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facility.hcpcs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
