# Generated by Django 4.0.3 on 2022-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_alter_hcpcs_unique_together_hcpcs_status_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hcpcs',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='hcpcs',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
