# Generated by Django 4.0.3 on 2022-04-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_alter_hcpcs_unique_together_alter_hcpcs_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='invoice_attachment',
        ),
        migrations.AlterField(
            model_name='chargeitem',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='facility.encounter'),
        ),
    ]
