# Generated by Django 4.0 on 2021-12-12 13:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'.", regex='^\\+254\\d{9}$')], verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Postal Address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('region', models.CharField(choices=[('COAST', 'Coast'), ('NORTH_EASTERN', 'North Eastern'), ('EASTERN', 'Eastern'), ('CENTRAL', 'Central'), ('RIFT_VALLEY', 'Rift Valley'), ('NYANZA', 'Nyanza'), ('NAIROBI', 'Nairobi')], max_length=32, verbose_name='Region')),
                ('county', models.CharField(choices=[('MOMBASA', 'Mombasa'), ('KWALE', 'Kwale'), ('KILIFI', 'Kilifi'), ('TANA_RIVER', 'Tana River'), ('LAMU', 'Lamu'), ('TAITA_TAVETA', 'Taita-Taveta'), ('GARISSA', 'Garissa'), ('WAJIR', 'Wajir'), ('MANDERA', 'Mandera'), ('MARSABIT', 'Marsabit'), ('ISIOLO', 'Isiolo'), ('MERU', 'Meru'), ('THARAKA_NITHI', 'Tharaka-Nithi'), ('EMBU', 'Embu'), ('KITUI', 'Kitui'), ('MACHAKOS', 'Machakos'), ('MAKUENI', 'Makueni'), ('NYANDARUA', 'Nyandarua'), ('NYERI', 'Nyeri'), ('KIRINYAGA', 'Kirinyaga'), ('MURANGA', "Murang'a"), ('KIAMBU', 'Kiambu'), ('TURKANA', 'Turkana'), ('WEST_POKOT', 'West Pokot'), ('SAMBURU', 'Samburu'), ('TRANS_NZOIA', 'Trans-Nzoia'), ('UASIN_GISHU', 'Uasin Gishu'), ('ELGEYO_MARAKWET', 'Elgeyo-Marakwet'), ('NANDI', 'Nandi'), ('BARINGO', 'Baringo'), ('LAIKIPIA', 'Laikipia'), ('NAKURU', 'Nakuru'), ('NAROK', 'Narok'), ('KAJIADO', 'Kajiado'), ('KERICHO', 'Kericho'), ('BOMET', 'Bomet'), ('KAKAMEGA', 'Kakamega'), ('VIHIGA', 'Vihiga'), ('BUNGOMA', 'Bungoma'), ('BUSIA', 'Busia'), ('SIAYA', 'Siaya'), ('KISUMU', 'Kisumu'), ('HOMA_BAY', 'Homa Bay'), ('MIGORI', 'Migori'), ('KISII', 'Kisii'), ('NYAMIRA', 'Nyamira'), ('NAIROBI', 'Nairobi')], max_length=32, verbose_name='County')),
                ('location', models.TextField(verbose_name='Detailed Location')),
                ('api_base_url', models.URLField(verbose_name='API Base URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('LAB_TECHNICIAN', 'Lab Technician'), ('SURGEON', 'Surgeon'), ('PHARMACIST', 'Pharmacist'), ('DENTIST', 'Dentist')], max_length=32, verbose_name='Health Worker Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='authentication.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tenure Start')),
                ('end', models.DateTimeField(null=True, verbose_name='Tenure End')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.healthfacility')),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employment_history', to='registry.healthworker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
