# Generated by Django 4.0.1 on 2022-01-18 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'.", regex='^\\+254\\d{9}$')], verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Postal Address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('county', models.CharField(choices=[('MOMBASA', 'Mombasa'), ('KWALE', 'Kwale'), ('KILIFI', 'Kilifi'), ('TANA_RIVER', 'Tana River'), ('LAMU', 'Lamu'), ('TAITA_TAVETA', 'Taita-Taveta'), ('GARISSA', 'Garissa'), ('WAJIR', 'Wajir'), ('MANDERA', 'Mandera'), ('MARSABIT', 'Marsabit'), ('ISIOLO', 'Isiolo'), ('MERU', 'Meru'), ('THARAKA_NITHI', 'Tharaka-Nithi'), ('EMBU', 'Embu'), ('KITUI', 'Kitui'), ('MACHAKOS', 'Machakos'), ('MAKUENI', 'Makueni'), ('NYANDARUA', 'Nyandarua'), ('NYERI', 'Nyeri'), ('KIRINYAGA', 'Kirinyaga'), ('MURANGA', "Murang'a"), ('KIAMBU', 'Kiambu'), ('TURKANA', 'Turkana'), ('WEST_POKOT', 'West Pokot'), ('SAMBURU', 'Samburu'), ('TRANS_NZOIA', 'Trans-Nzoia'), ('UASIN_GISHU', 'Uasin Gishu'), ('ELGEYO_MARAKWET', 'Elgeyo-Marakwet'), ('NANDI', 'Nandi'), ('BARINGO', 'Baringo'), ('LAIKIPIA', 'Laikipia'), ('NAKURU', 'Nakuru'), ('NAROK', 'Narok'), ('KAJIADO', 'Kajiado'), ('KERICHO', 'Kericho'), ('BOMET', 'Bomet'), ('KAKAMEGA', 'Kakamega'), ('VIHIGA', 'Vihiga'), ('BUNGOMA', 'Bungoma'), ('BUSIA', 'Busia'), ('SIAYA', 'Siaya'), ('KISUMU', 'Kisumu'), ('HOMA_BAY', 'Homa Bay'), ('MIGORI', 'Migori'), ('KISII', 'Kisii'), ('NYAMIRA', 'Nyamira'), ('NAIROBI', 'Nairobi')], max_length=32, verbose_name='County')),
                ('location', models.TextField(verbose_name='Detailed Location')),
                ('type', models.CharField(choices=[('HOSP', 'Hospital'), ('PSY', 'Psychiatry Clinic'), ('RH', 'Rehabilitation Hospital'), ('MBL', 'Medical Laboratory'), ('PHARM', 'Pharmacy'), ('PEDC', 'Pediatrics Clinic'), ('OPTC', 'Optometry Clinic'), ('DENT', 'Dental Clinic')], max_length=32, verbose_name='Type')),
                ('api_base_url', models.URLField(verbose_name='API Base URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('type', models.CharField(choices=[('PHYSICIAN', 'Physician'), ('NURSE', 'Nurse'), ('LAB_TECHNICIAN', 'Lab Technician'), ('SURGEON', 'Surgeon'), ('PHARMACIST', 'Pharmacist'), ('DENTIST', 'Dentist'), ('OPTICIAN', 'Optician')], max_length=32, verbose_name='Practitioner Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('released', models.BooleanField(default=True, verbose_name='Released?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='Tenure Start')),
                ('end', models.DateField(null=True, verbose_name='Tenure End')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.facility')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employment_history', to='registry.practitioner')),
            ],
            options={
                'ordering': ['-start'],
                'unique_together': {('practitioner', 'facility', 'start')},
            },
        ),
        migrations.CreateModel(
            name='RecordRating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rating')),
                ('review', models.TextField(verbose_name='Record Review')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ratings', to='registry.record')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='registry.tenure'),
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
    ]
