# Generated by Django 4.0.1 on 2022-01-20 14:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('visit_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('OPTICAL', 'Optical'), ('DENTAL', 'Dental')], max_length=16), size=None)),
                ('request_note', models.TextField(verbose_name='Request Note')),
                ('status', models.TextField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=16, verbose_name='Consent Request Status')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.tenure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time at facility'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConsentRequestTransition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('from_state', models.TextField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], max_length=16, verbose_name='From State')),
                ('to_state', models.TextField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=16, verbose_name='To State')),
                ('transition_time', models.DateTimeField(auto_now_add=True, verbose_name='Transition Time')),
                ('consent_request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transition_logs', to='registry.consentrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='records',
            field=models.ManyToManyField(related_name='consent_requests', to='registry.Record'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universally Unique IDentifier')),
                ('access_time', models.DateTimeField(verbose_name='Access Time')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.tenure')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='access_logs', to='registry.record')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
