# Generated by Django 4.0 on 2021-12-12 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_tenure_options_alter_tenure_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenure',
            name='end',
            field=models.DateField(null=True, verbose_name='Tenure End'),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tenure Start'),
        ),
    ]
