# Generated by Django 4.0.1 on 2022-01-20 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER_RELATIVE', 'Other Relative')], max_length=16, verbose_name="User's relationship to next of kin")),
                ('can_consent', models.BooleanField(default=False, verbose_name="Can consent on user's behalf?")),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='relatives',
            field=models.ManyToManyField(through='authentication.NextOfKin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='next_of_kin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
