# Generated by Django 4.0.3 on 2022-04-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_nextofkin_id_nextofkin_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nextofkin',
            unique_together={('user', 'next_of_kin')},
        ),
    ]
