# Generated by Django 4.0 on 2022-02-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentrequest',
            old_name='practitioner',
            new_name='requestor',
        ),
    ]
