# Generated by Django 4.0.3 on 2022-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_accesslog_created_accesslog_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='visit_type',
            field=models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('DENTAL', 'Dental'), ('OPTICAL', 'Optical')], default='OUTPATIENT', max_length=16),
            preserve_default=False,
        ),
    ]
