# Generated by Django 4.0.3 on 2022-05-03 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_accesslog_access_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordrating',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='recordrating',
            name='is_accurate',
        ),
        migrations.RemoveField(
            model_name='recordrating',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='recordrating',
            name='accuracy',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordrating',
            name='completeness',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
